### ISSUE TITLE
Screenshot of example dashboard?

### ISSUE THREAD

**Issue by jantman** [aws-solutions/real-time-insights-account-activity#1]
I found this project via the [AWS Answers post](https://aws.amazon.com/answers/account-management/real-time-insights-account-activity/) and the [solutions doc](https://docs.aws.amazon.com/solutions/latest/real-time-insights-account-activity/welcome.html). It looks _really_ interesting to me, but the one thing that seems to be missing from those docs is an example screenshot of the dashboard, to give people a feeling of what the default output of this looks like...

**Comment by ScottBrenner** [comment]
Agree! Best I could find is

![image](https://user-images.githubusercontent.com/416477/64899662-5e033e80-d641-11e9-9f50-efc057d9cd23.png)

from https://docs.aws.amazon.com/solutions/latest/real-time-insights-account-activity/appendix-b.html

**Comment by tomnight** [comment]
thanks for the feedback, 

Scott's right in that the most detailed documentation can be found on the solution home page: https://docs.aws.amazon.com/solutions/latest/real-time-insights-account-activity/welcome.html

We will add this request to the solutions backlog and review at the next release.

**Comment by aijunpeng** [comment]
Close the issue as the solution is deprecated.
