### ISSUE TITLE
Unable to deploy due to use of Nodejs 8.10 runtime for Lambda function

### ISSUE THREAD

**Issue by ctas582** [aws-solutions/real-time-insights-account-activity#5]
Similar to #4, CloudFormation fails to deploy `CustomResourceHelper` with the following error message:

> The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException)

**Comment by ericquinones** [comment]
Hi @ctas582 

Apologies for this issue. We will look into updating the solution but in the meantime, please try downloading the CloudFormation template ([link](https://s3.amazonaws.com/solutions-reference/real-time-insights-account-activity/latest/real-time-insights-account-activity.template)).

If you find the [line](https://github.com/awslabs/real-time-insights-account-activity/blob/master/deployment/real-time-insights-account-activity.template#L1045) where the Runtime for the `CustomResourceHelper` is defined, please change the value to `nodejs12.x`. Save the file and in the CloudFormation console, you will have the option to **upload a template file** when creating a stack.

If you use your modified template, you should be able to launch the solution. Again, we apologize that you had an issue. Please let us know if you are able to launch the solution with this update.

Thank you

**Comment by aijunpeng** [comment]
Close the issue as the solution is deprecated.
